# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LandCapApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LandCapApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'LandCapAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LandCapAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
